# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: {{ cookiecutter.project_slug }}
site_url: https://andgineer.github.io/{{ cookiecutter.package_name }}
site_author: Andrey Sorokin

# Repository
repo_name: {{ cookiecutter.project_slug }}
repo_url: https://github.com/andgineer/{{ cookiecutter.package_name }}
edit_uri: edit/master/docs
docs_dir: 'src/LANGUAGE'
site_dir: '../site/SITE_PREFIX'

plugins:
  - awesome-pages
  - search:
      lang: LANGUAGE

markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets:
      base_path: 'docs'

theme:
  name: material
  features:
    - toc.integrate
    - navigation.tracking
    - content.code.copy

extra:
  alternate:
    - name: English
      link: /{{ cookiecutter.package_name }}/
      lang: en
    - name: Русский
      link: /{{ cookiecutter.package_name }}/ru/
      lang: ru
