{% raw %}
# build docs from docstrings and markdown-file in folder docs
# publish them as github pages
#
#note for myself
#
# Do not forget to set git branch `gh-pages` as source for github pages.
# This branch auto-updated by `mkdocs gh-deploy`
#
name: docs
on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  deploy:
    env:
      PRIMARY_PYTHON_VERSION: '3.11'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PRIMARY_PYTHON_VERSION  }}
      - run: |
          pip install uv
          uv pip install ghp-import -r requirements.dev.txt --python=${{ env.PRIMARY_PYTHON_VERSION }}
      - run: ./scripts/build-docs.sh
      - run: |
          ghp-import --no-jekyll --push --force site
{% endraw %}